[tool.poetry]
name = "fastapi-manager"
version = "0.1.0"
description = ""
authors = ["Chaliuk Vladyslav <chaliukvladyslav@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.12.3"
sqlmodel = "^0.0.21"
asyncpg = "^0.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
